repository:
  # Repository basic settings
  name: stockholm-inventory-system
  description: "Stockholm Inventory Management System"
  homepage: ""
  topics: ["inventory", "management", "system", "stockholm"]
  
  # Repository access settings
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  
  # Default branch
  default_branch: main
  
  # Allow/disallow features
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  
  # Branch protection rules
  branch_protection:
    main:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        restrict_dismissals: false
      restrictions: null

# Teams and collaborators (adjust as needed)
collaborators: []

teams: []

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: frontend
    color: 1d76db
    description: Frontend related changes
  - name: backend
    color: 5319e7
    description: Backend related changes
  - name: inventory
    color: fbca04
    description: Inventory management features
