name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    # ===== FRONTEND =====
    - name: Install dependencies (frontend)
      working-directory: ./frontend
      run: npm ci

    - name: Run tests (frontend)
      working-directory: ./frontend
      run: |
        if [ -n "$(npm run | grep test)" ]; then
          npm test
        else
          echo "No tests configured"
        fi

    # ===== BACKEND =====
    - name: Install dependencies (backend)
      working-directory: ./backend
      run: npm ci

    - name: Run tests (backend)
      working-directory: ./backend
      run: |
        if [ -n "$(npm run | grep test)" ]; then
          npm test
        else
          echo "No tests configured"
        fi
